### ISSUE TITLE
no levanta el projecto.

### ISSUE THREAD

**Issue by andresbu93** [nachom48/prex-file-sharing#11]
Siguiendo las instrucciones tanto usando docker, como sin el, el proyecto lanza error al querer levantarlo:

Usando npm start (cambiando el DB_HOST a localhost):

![image](https://github.com/user-attachments/assets/afd50286-88ea-410f-8d50-08f6a806a8f4)

La base levanta bien:
![image](https://github.com/user-attachments/assets/2c7253ac-6b5b-40a3-9117-6545fb217503)

Usando docker-compose
![image](https://github.com/user-attachments/assets/69455b95-1d5b-4635-a5d4-02a203f812d0)

te animas a revisarlo?

**Comment by nachom48** [comment]
Realice cambios en el README para poder desplegarlo localmente y cambios en los scripts del package.json.
